### PR TITLE
Add LogDNA logging to staging and production

### PR DESCRIPTION
**Pull request by dfellis**
The log ingestion key is not considered a secret, it only allows writing logs, but I can rotate this key and we can make it a secret instead if desired.

### CODE REVIEW

**Comment by aguillenv** [comment]
> The log ingestion key is not considered a secret, it only allows writing logs, but I can rotate this key and we can make it a secret instead if desired.

They usually provide 2 keys, one that is "shareable" just to read/write logs and another one that is secret, not sure how logDna handles it.

**Comment by aguillenv** [comment]
> The log ingestion key is not considered a secret, it only allows writing logs, but I can rotate this key and we can make it a secret instead if desired.

They usually provide 2 keys, one that is "shareable" just to read/write logs and another one that is secret, not sure how logDna handles it.

**Review by aguillenv — APPROVED** [review]
As a follow up we should add more loggers around the diffing on apply and sync to have more data, right?

**Comment by dfellis** [comment]
> > The log ingestion key is not considered a secret, it only allows writing logs, but I can rotate this key and we can make it a secret instead if desired.
> 
> They usually provide 2 keys, one that is "shareable" just to read/write logs and another one that is secret, not sure how logDna handles it.

LogDNA actually has three types of keys. This one is write-only, another is read/write, and the third is read/write + API access.

**Pull request merged**
