### PR TITLE
fix: take cert from stdout if it exist

### LINKED ISSUE #1220: privkey generation fails on local tests
Modules like ELB rely on private key generation functions (on helpers.ts file).
There is an option for local environments, that just generates a key on the fly, and for other envs it just tries to read from a file, crashing if the file does not exist.
We can modify the test, to try reading the key from stdout. And if it does not exist, fallback to existing privkey file

### PR DESCRIPTION
**Pull request by yrobla**
In order to generate a private key, first try to take
the content from the generated openssl command. If it
does not exist, fallback to privkey content

Signed-off-by: Yolanda Robla <info@ysoft.biz>
Closes #1220

### CODE REVIEW

**Comment by yrobla** [comment]
there is a big difference, actually caused by `prettier` formatting.

**Review by dfellis — APPROVED** [review]

**Review by aguillenv — APPROVED** [review]

**Comment by dfellis** [comment]
Unfortunately it seems this PR doesn't actually work on Linux :( https://github.com/iasql/iasql-engine/runs/8194647676?check_suite_focus=true#step:6:9874

**Comment by dfellis** [comment]
BTW, why not invert the check? If there's a `.pem` file generated, use it, otherwise use the stdout value?

**Comment by yrobla** [comment]
> BTW, why not invert the check? If there's a `.pem` file generated, use it, otherwise use the stdout value?

makes sense, it will be simpler

**Review by aguillenv — APPROVED** [review]

**Pull request merged**
