### PR TITLE
Operation error message

### LINKED ISSUE #610: Set metadata for errors on `iasql_apply`
Revert https://github.com/iasql/iasql-engine/pull/598/files because there was some escape functionality missing from it. We should revive it with a test that forces and error and make sure that it works correctly

```
      error: QueryFailedError: syntax error at or near "s"
          at QueryFailedError.TypeORMError [as constructor] (/Users/luisfer/src/iasql-engine/src/error/TypeORMError.ts:7:9)
          at new QueryFailedError (/Users/luisfer/src/iasql-engine/src/error/QueryFailedError.ts:9:9)
          at PostgresQueryRunner.<anonymous> (/Users/luisfer/src/iasql-engine/src/driver/postgres/PostgresQueryRunner.ts:263:19)
          at step (/Users/luisfer/src/iasql-engine/node_modules/tslib/tslib.js:143:27)
          at Object.throw (/Users/luisfer/src/iasql-engine/node_modules/tslib/tslib.js:124:57)
          at rejected (/Users/luisfer/src/iasql-engine/node_modules/tslib/tslib.js:115:69)
          at processTicksAndRejections (node:internal/process/task_queues:96:5) {
        query: '\n' +
          '            update iasql_operation\n' +
          `            set end_date = now(), err = '{"message":"Forward progress halted. Some promises never resolved","metadata":{"generatorsToRun":[null],"generatorsSource":["\\"async () => {\\\\n                /* istanbul ignore next */\\\\n                cov_1sod6yl2sc().f[56]++;\\\\n                const out =\\\\n                /* istanbul ignore next */\\\\n                (cov_1sod6yl2sc().s[290]++, await r.mapper.cloud.create(e, context));\\\\n\\\\n                /* istanbul ignore next */\\\\n                cov_1sod6yl2sc().s[291]++;\\\\n\\\\n                if (out) {\\\\n                  /* istanbul ignore next */\\\\n                  cov_1sod6yl2sc().b[56][0]++;\\\\n                  const es =\\\\n                  /* istanbul ignore next */\\\\n                  (cov_1sod6yl2sc().s[292]++, Array.isArray(out) ?\\\\n                  /* istanbul ignore next */\\\\n                  (cov_1sod6yl2sc().b[57][0]++, out) :\\\\n                  /* istanbul ignore next */\\\\n                  (cov_1sod6yl2sc().b[57][1]++, [out]));\\\\n\\\\n                  /* istanbul ignore next */\\\\n                  cov_1sod6yl2sc().s[293]++;\\\\n                  es.forEach((e2) => {\\\\n                    /* istanbul ignore next */\\\\n                    cov_1sod6yl2sc().f[57]++;\\\\n                    cov_1sod6yl2sc().s[294]++;\\\\n                    // Mutate the original entity with the returned entity's properties so the actual\\\\n                    // record created is what is compared the next loop through\\\\n                    Object.keys(e2).forEach((k) => {\\\\n                      /* istanbul ignore next */\\\\n                      cov_1sod6yl2sc().f[58]++;\\\\n                      cov_1sod6yl2sc().s[295]++;\\\\n                      return e[k] = e2[k];\\\\n                    });\\\\n                  });\\\\n                } else\\\\n                /* istanbul ignore next */\\\\n                {\\\\n                  cov_1sod6yl2sc().b[56][1]++;\\\\n                }\\\\n              }\\""],"failures":["{\\"name\\":\\"Error\\",\\"message\\":\\"MalformedPolicyDocument: This policy contains invalid Json\\",\\"stack\\":\\"MalformedPolicyDocument: This policy contains invalid Json\\\\n    at deserializeAws_queryCreateRoleCommandError (/Users/luisfer/src/iasql-engine/node_modules/@aws-sdk/client-iam/dist-cjs/protocols/Aws_query.js:2785:24)\\\\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\\\\n    at /Users/luisfer/src/iasql-engine/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24\\\\n    at /Users/luisfer/src/iasql-engine/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20\\\\n    at StandardRetryStrategy.retry (/Users/luisfer/src/iasql-engine/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)\\\\n    at /Users/luisfer/src/iasql-engine/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22\\\\n    at AWS.newRole (/Users/luisfer/src/iasql-engine/src/services/gateways/aws.ts:181:18)\\\\n    at Crud.create [as createFn] (/Users/luisfer/src/iasql-engine/src/modules/aws_iam@0.0.1/index.ts:51:31)\\\\n    at Crud.create (/Users/luisfer/src/iasql-engine/src/modules/interfaces.ts:86:24)\\\\n    at /Users/luisfer/src/iasql-engine/src/services/iasql.ts:463:29\\"}"]}}'\n` +
          "            where opid = uuid('d86547e2-e7ca-a9aa-c8bc-e813d8137a88');\n" +
          '          ',
```

### PR DESCRIPTION
**Pull request by aguillenv**
Resolves #610

### CODE REVIEW

**Comment by depombo** [comment]
Btw at some point can we have a test where we artificially throw an error to make sure we are doing all the error handling correctly?

**Comment by aguillenv** [comment]
image

image

**Comment by aguillenv** [comment]
multiple failures during `apply` would be in the same message separated with an `\n`:
image

image

**Comment by aguillenv** [comment]
As comparison, if we recover the code that tries to save the complete error object with the `metadata` object it looks like this:
image

image


I personally prefer just the message as seen here: https://github.com/iasql/iasql-engine/pull/611#issuecomment-1090396292

@dfellis @depombo let me know your thoughts on this and I can commit either way and make this PR ready for review.

**Comment by dfellis** [comment]
> As comparison, if we recover the code that tries to save the complete error object with the `metadata` object it looks like this: image
> 
> image
> 
> I personally prefer just the message as seen here: [#611 (comment)](https://github.com/iasql/iasql-engine/pull/611#issuecomment-1090396292)
> 
> @dfellis @depombo let me know your thoughts on this and I can commit either way and make this PR ready for review.

What about a compromise? Just the error messages from each of the promises without the stack traces?

**Comment by dfellis** [comment]
> isn't that [#611 (comment)](https://github.com/iasql/iasql-engine/pull/611#issuecomment-1090396292)? or I'm not following?

So I only see one error in that screenshot, but in your second one you get the `Forward progress halted` and error messages plural.

The first one looks like it just picks one of the errors seemingly at random instead of showing them all?

**Comment by aguillenv** [comment]
> > isn't that [#611 (comment)](https://github.com/iasql/iasql-engine/pull/611#issuecomment-1090396292)? or I'm not following?
> 
> So I only see one error in that screenshot, but in your second one you get the `Forward progress halted` and error messages plural.
> 
> The first one looks like it just picks one of the errors seemingly at random instead of showing them all?

Oh no, it is exactly the same example in both. [#611 (comment)](https://github.com/iasql/iasql-engine/pull/611#issuecomment-1090396292) what it does is join messages in one string with separated with `\n`.

Maybe we can have the format 
```json
{ "message": ["error1", "error2"] }
```

instead of having them in one confusing string?

**Comment by dfellis** [comment]
> Maybe we can have the format
> 
> ```json
> { "message": ["error1", "error2"] }
> ```
> 
> instead of having them in one confusing string?

I like that!

**Comment by aguillenv** [comment]
Single error:
image

image


Multiple errors:
image

image

**Review by dfellis — APPROVED** [review]

**Pull request merged**
